Initial checkin of rna-index (samtools) workflow
amp-pd/amp-pd-workflows pull request #11
Opened 2019-09-06 17:35 UTC by wnojopra

This PR includes the rna-index workflow which executes samtools on a bam file.

Fixes #4 .

2019-09-10 21:40 UTC, mbookman requested changes

2019-09-10 21:40 UTC, mbookman commented on rna/rna-index/README.md
> +# RNAIndex with Samtools
Let's rename this directory to `rna-bam-sort-and-index` and workflow `RNABAMSortAndIndex`

2019-09-10 21:40 UTC, mbookman commented on rna/rna-index/README.md
> +This workflow runs samtools sort and samtools index on the STAR bam file.
s/the STAR bam/a BAM/

2019-09-10 21:40 UTC, mbookman commented on rna/rna-index/rna-index.inputs.json
> +  "RNAIndex.star_bam_file":"__INSERT_GCS_PATH_TO_BAM_FILE__",
Let's change `star_bam_file` to `input_bam_file` throughout.

2019-09-10 21:40 UTC, mbookman commented on rna/rna-index/rna-index.inputs.json
> +  "RNAIndex.num_cpu_cores": 4,
We ultimately used much more modest VM resources, which went into the 
[Controlling Cloud costs - sample use cases](https://support.terra.bio/hc/en-us/articles/360029772212-Controlling-Cloud-costs-sample-use-cases) Terra article:

> We found that we could index BAMs on a small, single-core VM (n1-standard-1) with a 200 GB disk.
> At preemptible rates of $0.01 per hour for the VM and $0.01 for the disk, these workflows cost pennies
> to complete for each sample.

Please update these inputs to reflect that machine shape.

2019-09-10 21:40 UTC, mbookman commented on rna/rna-index/rna-index.wdl
> +    if ! diff flagstat.old.txt flagstat.new.txt; then
Add a comment:

# Verifying the old and new BAMs produce the same flagstats

2019-09-10 21:51 UTC, mbookman requested changes

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/README.md
> +This workflow runs samtools sort and samtools index on a bam file.
s/bam/BAM

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.inputs.json
>  {
Please rename the file rna-bam-sort-and-index.inputs.json

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.inputs.json
>    "RNAIndex.sample_name": "__INSERT_SAMPLE_NAME__",
The input variable names here should all be changed from RNAIndex to RNABAMSortAndIndex

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.wdl
> +## This workflow runs samtools sort and samtools index on a bam file
s/bam/BAM

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.wdl
>  workflow RNAIndex {
s/RNAIndex/RNABAMSortAndIndex

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.wdl
>    call samtools_index {
Let's rename this call/task to `samtools_sort_and_index`

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.wdl
> +    # Verifying the old and new BAMs produce the same flagstats
Ah - to be consistent with the rest of the file:

echo "$(date "+%Y-%m-%d %H:%M:%S") Verifying the old and new BAMs produce the same flagstats"

2019-09-10 21:51 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-index.wdl
>      echo "$(date "+%Y-%m-%d %H:%M:%S") Creating soft link to old bam"
For the echo's, change "bam" to "BAM"

2019-09-10 22:13 UTC, mbookman requested changes
Looks good. A few small things.
Also please import these changes to Terra and verify that the workflow still runs.

2019-09-10 22:13 UTC, mbookman commented on rna/rna-bam-sort-and-index/README.md
> +
It then runs `samtools flagstat` on the old and new files and verifies that they are the same.

2019-09-10 22:13 UTC, mbookman commented on rna/rna-bam-sort-and-index/README.md
> +This workflow runs samtools sort and samtools index on a BAM file.
> `samtools sort` and `samtools index`

2019-09-10 22:38 UTC, wnojopra commented
I've re-tested these new changes [here](https://app.terra.bio/#workspaces/fc-amp-pd-alpha/STAR%20testing/job_history/63189eba-ec44-43fb-92f3-60fe140828bd) . Please keep in mind that because we cannot rename a workflow, I had to create a new one. Please disregard the old one.

2019-09-10 23:40 UTC, mbookman approved these changes
LGTM

2019-09-13 00:09 UTC, mbookman requested changes

2019-09-13 00:09 UTC, mbookman commented on rna/rna-bam-sort-and-index/rna-bam-sort-and-index.inputs.json
> +  "RNAIndex.sample_name": "__INSERT_SAMPLE_NAME__",
These sample inputs need to be updated to use `RNABAMSortAndIndex`.

2019-09-16 16:44 UTC, mbookman approved these changes
LGTM

2019-09-20 19:39 UTC, merged