Initial checkin of rna-collect-rna-seq-metrics workflow.
amp-pd/amp-pd-workflows pull request #18
Opened 2019-10-01 16:51 UTC by wnojopra

This PR includes the rna-collect-rna-seq-metrics workflow which executes picard CollectRnaSeqMetrics on a BAM file.

Fixes #16 .

2019-10-24 20:42 UTC, mbookman requested changes

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/README.md
> +This workflow runs `picard CollectRnaSeqMetrics` on a BAM file
This workflow runs [picard CollectRnaSeqMetrics](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.0.0/picard_analysis_CollectRnaSeqMetrics.php) on a BAM file.

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/rna-collect-rna-seq-metrics.inputs.json
> +  "RNACollectRnaSeqMetrics.ref_flat_file": "__INSERT_GCS_PATH_TO_REF_FLAT_FILE__",
gs://amp-pd-transcriptomics/inputs/reference/picard/gencode.v29.primary_assembly.annotation.Reflat_Picard.txt
gs://amp-pd-transcriptomics/inputs/reference/picard/gencode.v29.primary_assembly.annotation.RibosomalLocations.txt

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/rna-collect-rna-seq-metrics.wdl
> +  	  ribosomal_intervals_file=ribosomal_intervals_file,
There's an extra couple of spaces at the start of this line

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/rna-collect-rna-seq-metrics.wdl
> +      bam_file=bam_file,
Add a blank line after this one to separate the per-sample inputs from the reference inputs.

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/rna-collect-rna-seq-metrics.wdl
> +  File bam_file
Add a blank line after this one to separate the per-sample inputs from the reference inputs.

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/rna-collect-rna-seq-metrics.wdl
> +  File bam_file
Add a blank line after this one to separate the per-sample inputs from the reference inputs.

2019-10-24 20:42 UTC, mbookman commented on rna/rna-collect-rna-seq-metrics/rna-collect-rna-seq-metrics.wdl
> +}
nit: add a newline at the end of the file

2019-10-24 20:57 UTC, mbookman approved these changes
LGTM

2019-11-01 21:44 UTC, ha-duong-technome approved these changes

2019-11-01 21:45 UTC, merged