Update README for Picard metrics
amp-pd/amp-pd-workflows pull request #24
Opened 2019-10-30 19:10 UTC by wnojopra

2019-10-30 20:02 UTC, mbookman requested changes

2019-10-30 20:02 UTC, mbookman commented on rna/README.md
> +All of your workflow outputs will be stored in your Terra workspace bucket and the `sample` entity table will contain the paths to the outputs.
I think this paragraph belongs before the step-by-step instructions:

Thus if you set each workflow to run from the sample entity and set the outputs to update the sample entity, you can run a progression of workflows. All of your workflow outputs will be stored in your Terra workspace bucket and the `sample` entity table will contain the paths to the outputs.

2019-10-30 20:02 UTC, mbookman commented on rna/README.md
> +Additionally, you can run Picard tools to produce metrics on the BAM files.
All of the workflows are "optional", so I don't think we need to explicitly call this one out.

2019-10-30 20:02 UTC, mbookman commented on rna/README.md
> +- multiple_metrics_path (Array of STRINGS: paths to Multiple_metrics output files)
"in GCS"

2019-10-30 20:12 UTC, mbookman approved these changes
LGTM

2019-11-01 21:55 UTC, ha-duong-technome approved these changes

2019-11-01 21:55 UTC, merged