Initial checkin of salmon workflow.
amp-pd/amp-pd-workflows pull request #8
Opened 2019-09-05 21:24 UTC by wnojopra

This PR includes the rna-quantification workflow which executes salmon on a pair of fastq files.

Tested [here](https://app.terra.bio/#workspaces/fc-amp-pd-alpha/STAR%20testing/job_history/2272f6e3-e6ab-4f9e-95a7-a87b03cb36f3).

Fixes #2 .

2019-09-05 21:51 UTC, wnojopra commented on rna/rna-quantification/rna-quantification.inputs.json
> +  "RNAQuantification.salmon_index": "gs://amp-pd-data-rna-workflows/inputs/reference/salmon/Homo_sapiens.gencode.v29.all.salmon0.11.3_gencodeOption.index.tar.gz",
Matt, do I need to move this to gs://amp-pd-transcriptomics?

2019-09-05 22:04 UTC, mbookman requested changes

2019-09-05 22:04 UTC, mbookman commented on rna/rna-quantification/README.md
> +# RNASummarization with subread featureCounts
# RNAQuantification with salmon quant

2019-09-05 22:04 UTC, mbookman commented on rna/rna-quantification/README.md
> +A sample inputs.json file is included here with values derived from running workflows for AMP PD on [Terra.](https://app.terra.bio/)
The period should be outside of the hyperlink.

2019-09-05 22:04 UTC, mbookman commented on rna/rna-quantification/rna-quantification.inputs.json
> +  "RNAQuantification.salmon_index": "gs://amp-pd-data-rna-workflows/inputs/reference/salmon/Homo_sapiens.gencode.v29.all.salmon0.11.3_gencodeOption.index.tar.gz",
gs://amp-pd-transcriptomics/inputs/reference/salmon/Homo_sapiens.gencode.v29.all.salmon0.11.3_gencodeOption.index.tar.gz

2019-09-05 22:04 UTC, mbookman commented on rna/rna-quantification/rna-quantification.inputs.json
> +  "RNAQuantification.runtime_zones": "us-central1-c us-central1-b",
Let's be consistent with the zones we include as examples.
Let's standardize on `us-central1-a us-central1-b` in the inputs.json and the README.md.

2019-09-05 22:04 UTC, mbookman commented on rna/rna-quantification/rna-quantification.wdl
> +    UNZIPPED_GENE_MAP="$(echo ${gene_map} | sed -e "s/.gz$//")"
Change the sed expression to be enclosed by single quotes.
Single quotes suppresses $ expansion.

```
UNZIPPED_GENE_MAP="$(echo ${gene_map} | sed -e 's/.gz$//')"
```

2019-09-05 22:21 UTC, wnojopra commented
Thanks, all fixes committed.

2019-09-05 22:32 UTC, mbookman requested changes

2019-09-05 22:32 UTC, mbookman commented on rna/rna-quantification/README.md
> +This workflow runs the salmon command on a pair of FASTQ files
This workflow runs the `salmon quant` command on a pair of FASTQ files

2019-09-05 22:32 UTC, mbookman commented on rna/rna-quantification/rna-quantification.inputs.json
> +  "RNAQuantification.fastq_2": "${this.fastq1}",
```
  "RNAQuantification.sample_name": "__INSERT_SAMPLE_NAME__",
  "RNAQuantification.fastq_1": [ "__INSERT_GCS_PATHS_TO_FASTQ1__" ],
  "RNAQuantification.fastq_2": [ "__INSERT_GCS_PATHS_TO_FASTQ2__" ],
```

2019-09-05 22:33 UTC, mbookman commented on rna/rna-quantification/README.md
> +This workflow runs the salmon command on a pair of FASTQ files
Actually - should be "on a list of paired FASTQ files"

2019-09-05 23:58 UTC, mbookman approved these changes
LGTM

2019-09-06 00:30 UTC, mbookman commented on rna/rna-quantification/README.md
> +The gene map (GTF) file used was [GENCODE](https://www.gencodegenes.org/) v29.
Let's add:

The Salmon index is packaged as a gzipped TAR file as WDL draft-2 does not support the WDL Directory type.
The Salmon index was created with the following steps:


1- Download the GENCODE v29 FASTA file:

```
ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.transcripts.fa.gz
```

2- Run "salmon index" as:

```
salmon index \
  -t gencode.v29.transcripts.fa.gz \
  --gencode \
  -i Homo_sapiens.gencode.v29.all.salmon0.11.3_gencodeOption.index \
  --type quasi \
  -k 31
```

3- Build a gzipped TAR file for the Salmon workflow to pull just a single reference file:

```
tar cvfz Homo_sapiens.gencode.v29.all.salmon0.11.3_gencodeOption.index.tar.gz Homo_sapiens.gencode.v29.all.salmon0.11.3_gencodeOption.index/
```

2019-09-06 18:49 UTC, mbookman approved these changes
LGTM

2019-09-20 19:24 UTC, merged